services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    #restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # DB가 실제로 '준비'되었는지 확인하는 기능
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: spring
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # [내 컴퓨터 경로]:[컨테이너 내부 경로]
      - ./backend/uploads:/app/images
    depends_on:
      db:
        # db 컨테이너의 healthcheck가 통과하면 app 실행
        condition: service_healthy 

  nginx:
    build: 
      context: ./frontend
      args:
        - REACT_APP_KAKAOMAP_APIKEY=${REACT_APP_KAKAOMAP_APIKEY}
    container_name: nginx_webserver
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: