name: Deploy to Server

on:
  workflow_call: # 다른 워크플로우에서 호출 가능
  push:
    branches: [ "main" ]
    paths:
      - 'docker-compose.yml' # docker-compose 파일만 바뀔 때도 실행
  workflow_dispatch:

jobs:
  # 배포
  deploy:
    needs: build # 빌드가 성공한후 실행됨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 서버로 docker-compose.yml 전송
      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SERVER_USER }}/app" # 서버 내의 저장 위치

      # 서버 접속 후 .env 생성 및 배포
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script_stop: true
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            # .env 파일 생성 (환경 변수 일괄 주입)
            echo "${{ secrets.ENV_PROD }}" > .env
            # 업로드 폴더 생성 및 권한 부여
            mkdir -p uploads && chmod 777 uploads
            docker compose pull
            docker compose up -d
            docker image prune -f
